### ISSUE TITLE
Number of clusters for CIFAR10

### ISSUE THREAD

**Issue by Hiiragi0107** [Randl/kmeans_selfsuper#2]
Thanks for providing me with this code!
Overclustering - is it important?
What number of clusters do you think is reasonable for CIFAR10?

**Comment by Randl** [comment]
Probably for CIFAR-10 clustering wouldn't be too important. I'd try 10-15 clusters. The experiments should be cheap, so I'd just check a couple of options

**Comment by Hiiragi0107** [comment]
Thanks reply!
